name: Maven Deploy to GitHub Packages

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21 (required for your project)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Step 3: Create settings.xml for Maven authentication to GitHub Packages
      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>${{ secrets.MY_GITHUB_USERNAME }}</username>
      <password>${{ secrets.MY_GITHUB_TOKEN }}</password>
    </server>
  </servers>
</settings>" > ~/.m2/settings.xml

      # Step 4: Build and deploy to GitHub Packages
      - name: Build and deploy to GitHub Packages
        run: mvn clean deploy -DskipTests
