name: Maven Deploy to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Create settings.xml for Maven
        run: |
          mkdir -p ~/.m2
          echo "<settings>
  <servers>
    <server>
      <id>github</id>
      <username>${{ secrets.MY_GITHUB_USERNAME }}</username>
      <password>${{ secrets.MY_GITHUB_TOKEN }}</password>
    </server>
  </servers>
</settings>" > ~/.m2/settings.xml

      - name: Build and deploy
        run: mvn clean deploy -DskipTests
